
package com.zrt.portal.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VidyoPortalUserServicePortType", targetNamespace = "http://portal.vidyo.com/user/v1_1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VidyoPortalUserServicePortType {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.LogInResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "logIn")
    @WebResult(name = "LogInResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public LogInResponse logIn(
        @WebParam(name = "LogInRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        LogInRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.LinkEndpointResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws AccessRestrictedFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "linkEndpoint")
    @WebResult(name = "LinkEndpointResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public LinkEndpointResponse linkEndpoint(
        @WebParam(name = "LinkEndpointRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        LinkEndpointRequest parameter)
        throws AccessRestrictedFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.LogOutResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "logOut")
    @WebResult(name = "LogOutResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public LogOutResponse logOut(
        @WebParam(name = "LogOutRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        LogOutRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.MyEndpointStatusResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "myEndpointStatus")
    @WebResult(name = "MyEndpointStatusResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public MyEndpointStatusResponse myEndpointStatus(
        @WebParam(name = "MyEndpointStatusRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        MyEndpointStatusRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SearchMyContactsResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "searchMyContacts")
    @WebResult(name = "SearchMyContactsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SearchMyContactsResponse searchMyContacts(
        @WebParam(name = "SearchMyContactsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SearchMyContactsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.AddToMyContactsResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "addToMyContacts")
    @WebResult(name = "AddToMyContactsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public AddToMyContactsResponse addToMyContacts(
        @WebParam(name = "AddToMyContactsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        AddToMyContactsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RemoveFromMyContactsResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "removeFromMyContacts")
    @WebResult(name = "RemoveFromMyContactsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RemoveFromMyContactsResponse removeFromMyContacts(
        @WebParam(name = "RemoveFromMyContactsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        RemoveFromMyContactsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SearchResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "search")
    @WebResult(name = "SearchResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SearchResponse search(
        @WebParam(name = "SearchRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SearchRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SearchByEntityIDResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "searchByEntityID")
    @WebResult(name = "SearchByEntityIDResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SearchByEntityIDResponse searchByEntityID(
        @WebParam(name = "SearchByEntityIDRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SearchByEntityIDRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SearchByEmailResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "searchByEmail")
    @WebResult(name = "SearchByEmailResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SearchByEmailResponse searchByEmail(
        @WebParam(name = "SearchByEmailRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SearchByEmailRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SearchMembersResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "searchMembers")
    @WebResult(name = "SearchMembersResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SearchMembersResponse searchMembers(
        @WebParam(name = "SearchMembersRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SearchMembersRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SearchRoomsResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "searchRooms")
    @WebResult(name = "SearchRoomsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SearchRoomsResponse searchRooms(
        @WebParam(name = "SearchRoomsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SearchRoomsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetEntityByEntityIDResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getEntityByEntityID")
    @WebResult(name = "GetEntityByEntityIDResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetEntityByEntityIDResponse getEntityByEntityID(
        @WebParam(name = "GetEntityByEntityIDRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetEntityByEntityIDRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetEntityDetailsByEntityIDResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getEntityDetailsByEntityID")
    @WebResult(name = "GetEntityDetailsByEntityIDResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetEntityDetailsByEntityIDResponse getEntityDetailsByEntityID(
        @WebParam(name = "GetEntityDetailsByEntityIDRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetEntityDetailsByEntityIDRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SetThumbnailPhotoResponse
     * @throws FileTooLargeFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotAllowedThumbnailPhotoFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "setThumbnailPhoto")
    @WebResult(name = "SetThumbnailPhotoResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SetThumbnailPhotoResponse setThumbnailPhoto(
        @WebParam(name = "SetThumbnailPhotoRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SetThumbnailPhotoRequest parameter)
        throws FileTooLargeFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotAllowedThumbnailPhotoFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.InviteToConferenceResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "inviteToConference")
    @WebResult(name = "InviteToConferenceResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public InviteToConferenceResponse inviteToConference(
        @WebParam(name = "InviteToConferenceRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        InviteToConferenceRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CancelOutboundCallResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "cancelOutboundCall")
    @WebResult(name = "CancelOutboundCallResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CancelOutboundCallResponse cancelOutboundCall(
        @WebParam(name = "CancelOutboundCallRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CancelOutboundCallRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.JoinConferenceResponse
     * @throws GeneralFault_Exception
     * @throws WrongPINFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws ConferenceLockedFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "joinConference")
    @WebResult(name = "JoinConferenceResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public JoinConferenceResponse joinConference(
        @WebParam(name = "JoinConferenceRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        JoinConferenceRequest parameter)
        throws ConferenceLockedFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception, WrongPINFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.JoinIPCConferenceResponse
     * @throws GeneralFault_Exception
     * @throws WrongPINFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws ConferenceLockedFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "joinIPCConference")
    @WebResult(name = "JoinIPCConferenceResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public JoinIPCConferenceResponse joinIPCConference(
        @WebParam(name = "JoinIPCConferenceRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        JoinIPCConferenceRequest parameter)
        throws ConferenceLockedFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception, WrongPINFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.DirectCallResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "directCall")
    @WebResult(name = "DirectCallResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public DirectCallResponse directCall(
        @WebParam(name = "DirectCallRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        DirectCallRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetParticipantsResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getParticipants")
    @WebResult(name = "GetParticipantsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetParticipantsResponse getParticipants(
        @WebParam(name = "GetParticipantsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetParticipantsRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetLectureModeParticipantsResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getLectureModeParticipants")
    @WebResult(name = "GetLectureModeParticipantsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetLectureModeParticipantsResponse getLectureModeParticipants(
        @WebParam(name = "GetLectureModeParticipantsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetLectureModeParticipantsRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.LeaveConferenceResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "leaveConference")
    @WebResult(name = "LeaveConferenceResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public LeaveConferenceResponse leaveConference(
        @WebParam(name = "LeaveConferenceRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        LeaveConferenceRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.MuteAudioResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "muteAudio")
    @WebResult(name = "MuteAudioResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public MuteAudioResponse muteAudio(
        @WebParam(name = "MuteAudioRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        MuteAudioRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.UnmuteAudioResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "unmuteAudio")
    @WebResult(name = "UnmuteAudioResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public UnmuteAudioResponse unmuteAudio(
        @WebParam(name = "UnmuteAudioRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        UnmuteAudioRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.StartVideoResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "startVideo")
    @WebResult(name = "StartVideoResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public StartVideoResponse startVideo(
        @WebParam(name = "StartVideoRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        StartVideoRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.StopVideoResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "stopVideo")
    @WebResult(name = "StopVideoResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public StopVideoResponse stopVideo(
        @WebParam(name = "StopVideoRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        StopVideoRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.MyAccountResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "myAccount")
    @WebResult(name = "MyAccountResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public MyAccountResponse myAccount(
        @WebParam(name = "MyAccountRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        MyAccountRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreateRoomURLResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "createRoomURL")
    @WebResult(name = "CreateRoomURLResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreateRoomURLResponse createRoomURL(
        @WebParam(name = "CreateRoomURLRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CreateRoomURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RemoveRoomURLResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "removeRoomURL")
    @WebResult(name = "RemoveRoomURLResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RemoveRoomURLResponse removeRoomURL(
        @WebParam(name = "RemoveRoomURLRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        RemoveRoomURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreateRoomPINResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "createRoomPIN")
    @WebResult(name = "CreateRoomPINResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreateRoomPINResponse createRoomPIN(
        @WebParam(name = "CreateRoomPINRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CreateRoomPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RemoveRoomPINResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "removeRoomPIN")
    @WebResult(name = "RemoveRoomPINResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RemoveRoomPINResponse removeRoomPIN(
        @WebParam(name = "RemoveRoomPINRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        RemoveRoomPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreateRoomResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "createRoom")
    @WebResult(name = "CreateRoomResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreateRoomResponse createRoom(
        @WebParam(name = "CreateRoomRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CreateRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.DeleteRoomResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "deleteRoom")
    @WebResult(name = "DeleteRoomResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public DeleteRoomResponse deleteRoom(
        @WebParam(name = "DeleteRoomRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        DeleteRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.UpdatePasswordResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "updatePassword")
    @WebResult(name = "UpdatePasswordResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public UpdatePasswordResponse updatePassword(
        @WebParam(name = "UpdatePasswordRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        UpdatePasswordRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.UpdateLanguageResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "updateLanguage")
    @WebResult(name = "UpdateLanguageResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public UpdateLanguageResponse updateLanguage(
        @WebParam(name = "UpdateLanguageRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        UpdateLanguageRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.LockRoomResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "lockRoom")
    @WebResult(name = "LockRoomResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public LockRoomResponse lockRoom(
        @WebParam(name = "LockRoomRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        LockRoomRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.UnlockRoomResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "unlockRoom")
    @WebResult(name = "UnlockRoomResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public UnlockRoomResponse unlockRoom(
        @WebParam(name = "UnlockRoomRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        UnlockRoomRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SetMemberModeResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "setMemberMode")
    @WebResult(name = "SetMemberModeResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SetMemberModeResponse setMemberMode(
        @WebParam(name = "SetMemberModeRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SetMemberModeRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetRecordingProfilesResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getRecordingProfiles")
    @WebResult(name = "GetRecordingProfilesResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetRecordingProfilesResponse getRecordingProfiles(
        @WebParam(name = "GetRecordingProfilesRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetRecordingProfilesRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.StartRecordingResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws ResourceNotAvailableFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "startRecording")
    @WebResult(name = "StartRecordingResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public StartRecordingResponse startRecording(
        @WebParam(name = "StartRecordingRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        StartRecordingRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, ResourceNotAvailableFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetPortalVersionResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getPortalVersion")
    @WebResult(name = "GetPortalVersionResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetPortalVersionResponse getPortalVersion(
        @WebParam(name = "GetPortalVersionRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetPortalVersionRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.PauseRecordingResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "pauseRecording")
    @WebResult(name = "PauseRecordingResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public PauseRecordingResponse pauseRecording(
        @WebParam(name = "PauseRecordingRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        PauseRecordingRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.ResumeRecordingResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "resumeRecording")
    @WebResult(name = "ResumeRecordingResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public ResumeRecordingResponse resumeRecording(
        @WebParam(name = "ResumeRecordingRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        ResumeRecordingRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.StopRecordingResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "stopRecording")
    @WebResult(name = "StopRecordingResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public StopRecordingResponse stopRecording(
        @WebParam(name = "StopRecordingRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        StopRecordingRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreateWebcastURLResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "createWebcastURL")
    @WebResult(name = "CreateWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreateWebcastURLResponse createWebcastURL(
        @WebParam(name = "CreateWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CreateWebcastURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreateWebcastPINResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "createWebcastPIN")
    @WebResult(name = "CreateWebcastPINResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreateWebcastPINResponse createWebcastPIN(
        @WebParam(name = "CreateWebcastPINRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CreateWebcastPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RemoveWebcastURLResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "removeWebcastURL")
    @WebResult(name = "RemoveWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RemoveWebcastURLResponse removeWebcastURL(
        @WebParam(name = "RemoveWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        RemoveWebcastURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RemoveWebcastPINResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "removeWebcastPIN")
    @WebResult(name = "RemoveWebcastPINResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RemoveWebcastPINResponse removeWebcastPIN(
        @WebParam(name = "RemoveWebcastPINRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        RemoveWebcastPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetWebcastURLResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getWebcastURL")
    @WebResult(name = "GetWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetWebcastURLResponse getWebcastURL(
        @WebParam(name = "GetWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetWebcastURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetUserNameResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getUserName")
    @WebResult(name = "GetUserNameResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetUserNameResponse getUserName(
        @WebParam(name = "GetUserNameRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetUserNameRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetEntityByRoomKeyResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getEntityByRoomKey")
    @WebResult(name = "GetEntityByRoomKeyResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetEntityByRoomKeyResponse getEntityByRoomKey(
        @WebParam(name = "GetEntityByRoomKeyRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetEntityByRoomKeyRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetInviteContentResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getInviteContent")
    @WebResult(name = "GetInviteContentResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetInviteContentResponse getInviteContent(
        @WebParam(name = "GetInviteContentRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetInviteContentRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetRoomProfilesResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getRoomProfiles")
    @WebResult(name = "GetRoomProfilesResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetRoomProfilesResponse getRoomProfiles(
        @WebParam(name = "GetRoomProfilesRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetRoomProfileResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getRoomProfile")
    @WebResult(name = "GetRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetRoomProfileResponse getRoomProfile(
        @WebParam(name = "GetRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetRoomProfileRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SetRoomProfileResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "setRoomProfile")
    @WebResult(name = "SetRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SetRoomProfileResponse setRoomProfile(
        @WebParam(name = "SetRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SetRoomProfileRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RemoveRoomProfileResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "removeRoomProfile")
    @WebResult(name = "RemoveRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RemoveRoomProfileResponse removeRoomProfile(
        @WebParam(name = "RemoveRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        RemoveRoomProfileRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreateModeratorURLResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "createModeratorURL")
    @WebResult(name = "CreateModeratorURLResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreateModeratorURLResponse createModeratorURL(
        @WebParam(name = "CreateModeratorURLRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CreateModeratorURLRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RemoveModeratorURLResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "removeModeratorURL")
    @WebResult(name = "RemoveModeratorURLResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RemoveModeratorURLResponse removeModeratorURL(
        @WebParam(name = "RemoveModeratorURLRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        RemoveModeratorURLRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetModeratorURLResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getModeratorURL")
    @WebResult(name = "GetModeratorURLResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetModeratorURLResponse getModeratorURL(
        @WebParam(name = "GetModeratorURLRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetModeratorURLRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetModeratorURLWithTokenResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getModeratorURLWithToken")
    @WebResult(name = "GetModeratorURLWithTokenResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetModeratorURLWithTokenResponse getModeratorURLWithToken(
        @WebParam(name = "GetModeratorURLWithTokenRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetModeratorURLWithTokenRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreateModeratorPINResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws InvalidModeratorPINFormatFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "createRoomModeratorPIN")
    @WebResult(name = "CreateModeratorPINResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreateModeratorPINResponse createModeratorPIN(
        @WebParam(name = "CreateModeratorPINRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CreateModeratorPINRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, InvalidModeratorPINFormatFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RemoveModeratorPINResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "removeRoomModeratorPIN")
    @WebResult(name = "RemoveModeratorPINResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RemoveModeratorPINResponse removeModeratorPIN(
        @WebParam(name = "RemoveModeratorPINRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        RemoveModeratorPINRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetConferenceIDResponse
     * @throws InPointToPointCallFault_Exception
     * @throws GeneralFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getConferenceID")
    @WebResult(name = "GetConferenceIDResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetConferenceIDResponse getConferenceID(
        @WebParam(name = "GetConferenceIDRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetConferenceIDRequest parameter)
        throws GeneralFault_Exception, InPointToPointCallFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GenerateAuthTokenResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws EndpointNotBoundFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "generateAuthToken")
    @WebResult(name = "GenerateAuthTokenResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GenerateAuthTokenResponse generateAuthToken(
        @WebParam(name = "GenerateAuthTokenRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GenerateAuthTokenRequest parameter)
        throws EndpointNotBoundFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreateScheduledRoomResponse
     * @throws GeneralFault_Exception
     * @throws ScheduledRoomCreationFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "createScheduledRoom")
    @WebResult(name = "CreateScheduledRoomResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreateScheduledRoomResponse createScheduledRoom(
        @WebParam(name = "CreateScheduledRoomRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CreateScheduledRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, ScheduledRoomCreationFault_Exception, SeatLicenseExpiredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.DeleteScheduledRoomResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws RoomNotFoundFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "deleteScheduledRoom")
    @WebResult(name = "DeleteScheduledRoomResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public DeleteScheduledRoomResponse deleteScheduledRoom(
        @WebParam(name = "DeleteScheduledRoomRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        DeleteScheduledRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreatePublicRoomResponse
     * @throws GeneralFault_Exception
     * @throws PublicRoomCreationFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws NotAllowedToCreateFault_Exception
     */
    @WebMethod(action = "createPublicRoom")
    @WebResult(name = "CreatePublicRoomResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreatePublicRoomResponse createPublicRoom(
        @WebParam(name = "CreatePublicRoomRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        CreatePublicRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotAllowedToCreateFault_Exception, NotLicensedFault_Exception, PublicRoomCreationFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.UpdatePublicRoomDescriptionResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws RoomNotFoundFault_Exception
     * @throws PublicRoomDescUpdationFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "updatePublicRoomDescription")
    @WebResult(name = "UpdatePublicRoomDescriptionResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public UpdatePublicRoomDescriptionResponse updatePublicRoomDescription(
        @WebParam(name = "UpdatePublicRoomDescriptionRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        UpdatePublicRoomDescriptionRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, PublicRoomDescUpdationFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetPortalFeaturesResponse
     * @throws GeneralFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getPortalFeatures")
    @WebResult(name = "GetPortalFeaturesResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetPortalFeaturesResponse getPortalFeatures(
        @WebParam(name = "GetPortalFeaturesRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SetEndpointDetailsResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws EndpointNotBoundFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "setEndpointDetails")
    @WebResult(name = "SetEndpointDetailsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SetEndpointDetailsResponse setEndpointDetails(
        @WebParam(name = "SetEndpointDetailsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SetEndpointDetailsRequest parameter)
        throws EndpointNotBoundFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetActiveSessionsResponse
     * @throws GeneralFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getActiveSessions")
    @WebResult(name = "GetActiveSessionsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetActiveSessionsResponse getActiveSessions(
        @WebParam(name = "GetActiveSessionsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.LogoutAllOtherSessionsResponse
     * @throws GeneralFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "logoutAllOtherSessions")
    @WebResult(name = "LogoutAllOtherSessionsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public LogoutAllOtherSessionsResponse logoutAllOtherSessions(
        @WebParam(name = "LogoutAllOtherSessionsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.DisconnectConferenceAllResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "disconnectConferenceAll")
    @WebResult(name = "disconnectConferenceAllResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public DisconnectConferenceAllResponse disconnectConferenceAll(
        @WebParam(name = "disconnectConferenceAllRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        DisconnectConferenceAllRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.MuteAudioServerAllResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "muteAudioServerAll")
    @WebResult(name = "muteAudioServerAllResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public MuteAudioServerAllResponse muteAudioServerAll(
        @WebParam(name = "muteAudioServerAllRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        MuteAudioServerAllRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.MuteAudioClientAllResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "muteAudioClientAll")
    @WebResult(name = "muteAudioClientAllResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public MuteAudioClientAllResponse muteAudioClientAll(
        @WebParam(name = "muteAudioClientAllRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        MuteAudioClientAllRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.MuteVideoServerAllResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "muteVideoServerAll")
    @WebResult(name = "muteVideoServerAllResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public MuteVideoServerAllResponse muteVideoServerAll(
        @WebParam(name = "muteVideoServerAllRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        MuteVideoServerAllRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.MuteVideoClientAllResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "muteVideoClientAll")
    @WebResult(name = "muteVideoClientAllResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public MuteVideoClientAllResponse muteVideoClientAll(
        @WebParam(name = "muteVideoClientAllRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        MuteVideoClientAllRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param onetimeAccessRequest
     * @return
     *     returns com.zrt.portal.user.OnetimeAccessResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getOnetimeAccessUrl")
    @WebResult(name = "OnetimeAccessResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "onetimeAccessResponse")
    public OnetimeAccessResponse getOnetimeAccessUrl(
        @WebParam(name = "OnetimeAccessRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "onetimeAccessRequest")
        Object onetimeAccessRequest)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param roomAccessOptionsRequest
     * @return
     *     returns com.zrt.portal.user.RoomAccessOptionsResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getRoomAccessOptions")
    @WebResult(name = "RoomAccessOptionsResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "roomAccessOptionsResponse")
    public RoomAccessOptionsResponse getRoomAccessOptions(
        @WebParam(name = "RoomAccessOptionsRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "roomAccessOptionsRequest")
        RoomAccessOptionsRequest roomAccessOptionsRequest)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param portalPrefixRequest
     * @return
     *     returns com.zrt.portal.user.PortalPrefixResponse
     * @throws GeneralFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws PrefixNotConfiguredFault_Exception
     */
    @WebMethod(action = "getPortalPrefix")
    @WebResult(name = "PortalPrefixResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "portalPrefixResponse")
    public PortalPrefixResponse getPortalPrefix(
        @WebParam(name = "PortalPrefixRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "portalPrefixRequest")
        Object portalPrefixRequest)
        throws GeneralFault_Exception, NotLicensedFault_Exception, PrefixNotConfiguredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetLoginAndWelcomeBannerResponse
     * @throws GeneralFault_Exception
     * @throws FeatureNotAvailableFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getLoginAndWelcomeBanner")
    @WebResult(name = "getLoginAndWelcomeBannerResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetLoginAndWelcomeBannerResponse getLoginAndWelcomeBanner(
        @WebParam(name = "getLoginAndWelcomeBannerRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetLoginAndWelcomeBannerRequest parameter)
        throws FeatureNotAvailableFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetUserAccountTypeResponse
     * @throws GeneralFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getUserAccountType")
    @WebResult(name = "getUserAccountTypeResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetUserAccountTypeResponse getUserAccountType(
        @WebParam(name = "getUserAccountTypeRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetUserAccountTypeRequest parameter)
        throws GeneralFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.StartLectureModeResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "startLectureMode")
    @WebResult(name = "StartLectureModeResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public StartLectureModeResponse startLectureMode(
        @WebParam(name = "StartLectureModeRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        StartLectureModeRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.StopLectureModeResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "stopLectureMode")
    @WebResult(name = "StopLectureModeResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public StopLectureModeResponse stopLectureMode(
        @WebParam(name = "StopLectureModeRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        StopLectureModeRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RaiseHandResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "raiseHand")
    @WebResult(name = "RaiseHandResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RaiseHandResponse raiseHand(
        @WebParam(name = "RaiseHandRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.UnraiseHandResponse
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "unraiseHand")
    @WebResult(name = "UnraiseHandResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public UnraiseHandResponse unraiseHand(
        @WebParam(name = "UnraiseHandRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.DismissRaisedHandResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "dismissRaisedHand")
    @WebResult(name = "DismissRaisedHandResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public DismissRaisedHandResponse dismissRaisedHand(
        @WebParam(name = "DismissRaisedHandRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        DismissRaisedHandRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.DismissAllRaisedHandResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "dismissAllRaisedHand")
    @WebResult(name = "DismissAllRaisedHandResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public DismissAllRaisedHandResponse dismissAllRaisedHand(
        @WebParam(name = "DismissAllRaisedHandRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        DismissAllRaisedHandRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.SetPresenterResponse
     * @throws GeneralFault_Exception
     * @throws ControlMeetingFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "setPresenter")
    @WebResult(name = "SetPresenterResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public SetPresenterResponse setPresenter(
        @WebParam(name = "SetPresenterRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        SetPresenterRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.RemovePresenterResponse
     * @throws ControlMeetingFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "removePresenter")
    @WebResult(name = "RemovePresenterResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public RemovePresenterResponse removePresenter(
        @WebParam(name = "RemovePresenterRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        RemovePresenterRequest parameter)
        throws ControlMeetingFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetVidyoReplayLibraryResponse
     * @throws GeneralFault_Exception
     * @throws VidyoReplayNotAvailableFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getVidyoReplayLibrary")
    @WebResult(name = "GetVidyoReplayLibraryResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetVidyoReplayLibraryResponse getVidyoReplayLibrary(
        @WebParam(name = "GetVidyoReplayLibraryRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetVidyoReplayLibraryRequest parameter)
        throws GeneralFault_Exception, NotLicensedFault_Exception, VidyoReplayNotAvailableFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.WhatIsMyIPAddressResponse
     * @throws GeneralFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "whatIsMyIPAddress")
    @WebResult(name = "WhatIsMyIPAddressResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public WhatIsMyIPAddressResponse whatIsMyIPAddress(
        @WebParam(name = "WhatIsMyIPAddressRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        WhatIsMyIPAddressRequest parameter)
        throws GeneralFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetChangePasswordHtmlUrlWithTokenResponse
     * @throws GeneralFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getChangePasswordHtmlUrlWithToken")
    @WebResult(name = "GetChangePasswordHtmlUrlWithTokenResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetChangePasswordHtmlUrlWithTokenResponse getChangePasswordHtmlUrlWithToken(
        @WebParam(name = "GetChangePasswordHtmlUrlWithTokenRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetChangePasswordHtmlUrlWithTokenRequest parameter)
        throws GeneralFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.GetPINLengthRangeResponse
     * @throws GeneralFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "getPINLengthRange")
    @WebResult(name = "GetPINLengthRangeResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public GetPINLengthRangeResponse getPINLengthRange(
        @WebParam(name = "GetPINLengthRangeRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        GetPINLengthRangeRequest parameter)
        throws GeneralFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.zrt.portal.user.SilenceSpeakerServerType
     * @throws InvalidParticipantFault_Exception
     * @throws InvalidConferenceFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "silenceSpeakerServer")
    @WebResult(name = "SilenceSpeakerServerResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameters")
    public SilenceSpeakerServerType silenceSpeakerServer(
        @WebParam(name = "SilenceSpeakerServerRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameters")
        SilenceSpeakerServerType parameters)
        throws InvalidConferenceFault_Exception, InvalidParticipantFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.zrt.portal.user.SilenceSpeakerServerType
     * @throws InvalidConferenceFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "silenceSpeakerServerAll")
    @WebResult(name = "SilenceSpeakerServerAllResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameters")
    public SilenceSpeakerServerType silenceSpeakerServerAll(
        @WebParam(name = "SilenceSpeakerServerAllRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameters")
        SilenceSpeakerServerType parameters)
        throws InvalidConferenceFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.zrt.portal.user.GetLogAggregationServerResponse
     * @throws LogAggregationDisabledFault_Exception
     */
    @WebMethod(action = "getLogAggregationServer")
    @WebResult(name = "getLogAggregationServerResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameters")
    public GetLogAggregationServerResponse getLogAggregationServer(
        @WebParam(name = "getLogAggregationServerRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameters")
        GetLogAggregationServerRequest parameters)
        throws LogAggregationDisabledFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.zrt.portal.user.CreateTestcallRoomResponse
     * @throws TestcallRoomCreationFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws SeatLicenseExpiredFault_Exception
     * @throws NotLicensedFault_Exception
     */
    @WebMethod(action = "createTestcallRoom")
    @WebResult(name = "CreateTestcallRoomResponse", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
    public CreateTestcallRoomResponse createTestcallRoom(
        @WebParam(name = "CreateTestcallRoomRequest", targetNamespace = "http://portal.vidyo.com/user/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, SeatLicenseExpiredFault_Exception, TestcallRoomCreationFault_Exception
    ;

}
