
package com.zrt.portal.replay;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VidyoReplayContentManagementService", targetNamespace = "http://replay.vidyo.com/apiservice", wsdlLocation = "http://replay.byshang.cn/replay/services/VidyoReplayContentManagementService?wsdl")
public class VidyoReplayContentManagementService
    extends Service
{

    private final static URL VIDYOREPLAYCONTENTMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException VIDYOREPLAYCONTENTMANAGEMENTSERVICE_EXCEPTION;
    private final static QName VIDYOREPLAYCONTENTMANAGEMENTSERVICE_QNAME = new QName("http://replay.vidyo.com/apiservice", "VidyoReplayContentManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://replay.byshang.cn/replay/services/VidyoReplayContentManagementService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIDYOREPLAYCONTENTMANAGEMENTSERVICE_WSDL_LOCATION = url;
        VIDYOREPLAYCONTENTMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public VidyoReplayContentManagementService() {
        super(__getWsdlLocation(), VIDYOREPLAYCONTENTMANAGEMENTSERVICE_QNAME);
    }

    public VidyoReplayContentManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIDYOREPLAYCONTENTMANAGEMENTSERVICE_QNAME, features);
    }

    public VidyoReplayContentManagementService(URL wsdlLocation) {
        super(wsdlLocation, VIDYOREPLAYCONTENTMANAGEMENTSERVICE_QNAME);
    }

    public VidyoReplayContentManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIDYOREPLAYCONTENTMANAGEMENTSERVICE_QNAME, features);
    }

    public VidyoReplayContentManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VidyoReplayContentManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VidyoReplayContentManagementServicePortType
     */
    @WebEndpoint(name = "VidyoReplayContentManagementServicePort")
    public VidyoReplayContentManagementServicePortType getVidyoReplayContentManagementServicePort() {
        return super.getPort(new QName("http://replay.vidyo.com/apiservice", "VidyoReplayContentManagementServicePort"), VidyoReplayContentManagementServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VidyoReplayContentManagementServicePortType
     */
    @WebEndpoint(name = "VidyoReplayContentManagementServicePort")
    public VidyoReplayContentManagementServicePortType getVidyoReplayContentManagementServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://replay.vidyo.com/apiservice", "VidyoReplayContentManagementServicePort"), VidyoReplayContentManagementServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIDYOREPLAYCONTENTMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw VIDYOREPLAYCONTENTMANAGEMENTSERVICE_EXCEPTION;
        }
        return VIDYOREPLAYCONTENTMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
