
package com.zrt.portal.admin;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GroupNotFoundFault", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
public class GroupNotFoundFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GroupNotFoundFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GroupNotFoundFault_Exception(String message, GroupNotFoundFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GroupNotFoundFault_Exception(String message, GroupNotFoundFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.zrt.portal.admin.GroupNotFoundFault
     */
    public GroupNotFoundFault getFaultInfo() {
        return faultInfo;
    }

}
