
package com.zrt.portal.admin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VidyoPortalAdminService", targetNamespace = "http://portal.vidyo.com/admin/v1_1", wsdlLocation = "http://api.byshang.cn/services/v1_1/VidyoPortalAdminService?wsdl")
public class VidyoPortalAdminService
    extends Service
{

    private final static URL VIDYOPORTALADMINSERVICE_WSDL_LOCATION;
    private final static WebServiceException VIDYOPORTALADMINSERVICE_EXCEPTION;
    private final static QName VIDYOPORTALADMINSERVICE_QNAME = new QName("http://portal.vidyo.com/admin/v1_1", "VidyoPortalAdminService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.byshang.cn/services/v1_1/VidyoPortalAdminService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIDYOPORTALADMINSERVICE_WSDL_LOCATION = url;
        VIDYOPORTALADMINSERVICE_EXCEPTION = e;
    }

    public VidyoPortalAdminService() {
        super(__getWsdlLocation(), VIDYOPORTALADMINSERVICE_QNAME);
    }

    public VidyoPortalAdminService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIDYOPORTALADMINSERVICE_QNAME, features);
    }

    public VidyoPortalAdminService(URL wsdlLocation) {
        super(wsdlLocation, VIDYOPORTALADMINSERVICE_QNAME);
    }

    public VidyoPortalAdminService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIDYOPORTALADMINSERVICE_QNAME, features);
    }

    public VidyoPortalAdminService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VidyoPortalAdminService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VidyoPortalAdminServicePortType
     */
    @WebEndpoint(name = "VidyoPortalAdminServicePort")
    public VidyoPortalAdminServicePortType getVidyoPortalAdminServicePort() {
        return super.getPort(new QName("http://portal.vidyo.com/admin/v1_1", "VidyoPortalAdminServicePort"), VidyoPortalAdminServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VidyoPortalAdminServicePortType
     */
    @WebEndpoint(name = "VidyoPortalAdminServicePort")
    public VidyoPortalAdminServicePortType getVidyoPortalAdminServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://portal.vidyo.com/admin/v1_1", "VidyoPortalAdminServicePort"), VidyoPortalAdminServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIDYOPORTALADMINSERVICE_EXCEPTION!= null) {
            throw VIDYOPORTALADMINSERVICE_EXCEPTION;
        }
        return VIDYOPORTALADMINSERVICE_WSDL_LOCATION;
    }

}
